### PR TITLE
feat(react-example): add react example to project

### PR DESCRIPTION
**Pull request by pyatyispyatil**
- Rewrote the whole example in React.
 - Made flamechart wrappers for React (maybe it's worth adding them to the dist?).
 - Reworked the view so that it was more convenient to use.
 - Added an example of a custom flame chart with two charts.
 - Changed node selection api - now event contains one object with data and type. This made it much easier to type this place.

### CODE REVIEW

**Comment by Smrtnyk** [comment]
first of all, awesome and inspiring work
I really can learn a lot from you in this area of development

I have tried out the deployed branch and compared it a bit against the currently deployed one from master
I might be wrong, but on scrolling it seems like there is a slight lag now when flame chart expands, where on master it is pretty smooth
also on master chart looks bit more sharp

**Comment by pyatyispyatil** [comment]
> first of all, awesome and inspiring work
I really can learn a lot from you in this area of development

It seems to be a completely unremarkable code, as for me ... But thanks, I'm glad that this experience is useful to you.)

Can you take a screenshot and record a comparison video? On my macbook they look exactly the same. Maybe it's in the OS and screen resolution?

**Comment by Smrtnyk** [comment]
you are right, I was on my company laptop and it is obviously unreliable

now when I am looking at it at home, everything is smooth and great

**Review by Smrtnyk — APPROVED** [review]
LGTM

**Pull request merged**
