### PR TITLE
Bump deps

### PR DESCRIPTION
**Pull request by Smrtnyk**
Bumping some deps, most importantly typescript to newest version, since I plan to work again on finalizing strict types in typescript.

### CODE REVIEW

**Comment by Smrtnyk** [comment]
seems like `rollup-plugin-uglify` requires rollup < 2 but we use newer one
not sure how this worked before

**Comment by Smrtnyk** [comment]
I have pushed one more commit that reduces type issues in strict mode to 10
not sure how to proceed with those
If you will have some time @pyatyispyatil maybe you could have a look, since we are very close now to having strict set to true

**Review by pyatyispyatil — APPROVED** [review]

**Comment by pyatyispyatil** [comment]
Everything is fine
Good to see you again.)

**Comment by Smrtnyk** [comment]
I was unfortunately very busy at work, and some stuff going on in private life
but I always planned to come back working on this repo since I really love it

anyway, hope everything is fine at your side, especially with stuff going on in the world currently

**Comment by pyatyispyatil** [comment]
Well, not everything is so good, considering that the world is heading towards the abyss.)
But what to do. I decided to stay in Moscow and hope that I will not be mobilized. It seems that there are no prerequisites for this yet.

**Pull request merged**
