### PR TITLE
feat(dead-code): add dead code script

### PR DESCRIPTION
**Pull request by Smrtnyk**
this script detects all unused export keywords

This may be opinionated, I just thought it might be convenient and less noisy to not export things that are not consumed.
Please let me know if you think this is unnecessary.

### CODE REVIEW

**Comment by pyatyispyatil** [comment]
Hmm, it seems to me that type exports are still worth keeping, as they can be useful to users of the library.

**Comment by Smrtnyk** [comment]
> Hmm, it seems to me that type exports are still worth keeping, as they can be useful to users of the library.

seems like these are not reexported from index.ts file then, should they be?

**Comment by pyatyispyatil** [comment]
I think it would be nice to add them.)

**Comment by Smrtnyk** [comment]
there was another PR that added exports so this PR is probably not needed at all

**Pull request closed without merging**
